name: Main
on:
  push:
    branches:
      - stable
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read .nvmrc
        id: nvm
        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check code formatting
        run: yarn run format:check
      - name: Lint
        run: yarn run lint
      - name: Check types
        run: yarn run types-check
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test:coverage --ci --silent --forceExit
      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.14
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/lcov.info
