name: Main
on:
  push:
    branches:
      - stable
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Read .nvmrc
        id: nvm
        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
      - name: Install dependencies
        run: yarn install
      - name: Check code formatting
        run: yarn run format:check
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test
      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/lcov.info
